// Tareas
export const CREAR_TAREA = "CREAR_TAREA";
export const OBTENER_TAREA = "OBTENER_TAREA";
export const ELIMINAR_TAREA = "ELIMINAR_TAREA";
export const ACTUALIZAR_TAREA = "ACTUALIZAR_TAREA";
export const ACTUALIZAR_ESTADO = "ACTUALIZAR_ESTADO";
export const PAUSAR_TAREA = "PAUSAR_TAREA";
export const REINICIAR_TAREA = "REINICIAR_TAREA";
export const COMPLETAR_TAREA = "COMPLETAR_TAREA";
export const GENERAR_TAREAS = "GENERAR_TAREAS";
export const OBTENER_TAREAS = "OBTENER_TAREAS";
