// Tareas
export const CREAR_TAREA = "CREAR_TAREA";
export const OBTENER_TAREA = "OBTENER_TAREA";
export const ELIMINAR_TAREA = "ELIMINAR_TAREA";
export const ACTUALIZAR_TAREA = "ACTUALIZAR_TAREA";
export const ACTUALIZAR_ESTADO = "ACTUALIZAR_ESTADO";
export const PAUSAR_TAREA = "PAUSAR_TAREA";
